import { CharacterData, AlignmentOption } from '@/types/character';

export const getCharacterData = (): CharacterData => ({
  steps: [
    { id: 'race', number: 1, title: 'Раса', icon: 'user' },
    { id: 'subrace', number: 2, title: 'Подраса', icon: 'star' },
    { id: 'class', number: 3, title: 'Класс', icon: 'sword' },
    { id: 'origin', number: 4, title: 'Происхождение', icon: 'compass' },
    { id: 'alignment', number: 5, title: 'Мировоззрение', icon: 'balance' },
    { id: 'stats', number: 6, title: 'Характеристики', icon: 'chart' },
    { id: 'spells', number: 7, title: 'Заклинания', icon: 'sparkles' },
  ],
  races: [
    { id: 'human', name: 'Люди', description: 'Самые распространённые существа в мире.', modifier: { strength: 1, agility: 1, constitution: 1, intelligence: 1, wisdom: 1, charisma: 1 } },
    { id: 'elf', name: 'Эльфы', description: 'Долгоживущие существа с острым чувством магии.', modifier: { agility: 2, wisdom: 1 } },
    { id: 'dwarf', name: 'Дварфы', description: 'Мастера кузнечного дела.', modifier: { strength: 2, constitution: 2 } },
    { id: 'gnome', name: 'Гномы', description: 'Маленькие, но умные существа с любовью к механизмам.', modifier: { intelligence: 2 } },
    { id: 'halfling', name: 'Полурослики', description: 'Маленькие, но ловкие существа.', modifier: { agility: 2, charisma: 1 } },
    { id: 'orc', name: 'Полуорки', description: 'Сильные и выносливые воины.', modifier: { strength: 2, constitution: 1, charisma: -1 } },
    { id: 'dragonborn', name: 'Драконорожденные', description: 'Потомки драконов с врожденными способностями.', modifier: { strength: 2, charisma: 1 } },
    { id: 'tiefling', name: 'Тифлинг', description: 'Потомки демонов с магическими способностями.', modifier: { intelligence: 1, charisma: 2 } },
  ],
  subRaces: [
    { id: 'high-elf', name: 'Высший', raceId: 'elf', description: 'Эльфы, посвятившие себя изучению магии.', modifier: { intelligence: 1, charisma: 1 }, imageUrl: '/create_char/subrace/mobile-subrace/Зариэль.svg' },
    { id: 'wood-elf', name: 'Лесной', raceId: 'elf', description: 'Эльфы, живущие в гармонии с природой.', modifier: { agility: 1, wisdom: 1 }, imageUrl: '/create_char/subrace/mobile-subrace/Зариэль.svg' },
    { id: 'drow', name: 'Дроу', raceId: 'elf', description: 'Тёмные эльфы, обитающие в Подземельях.', modifier: { charisma: 1 }, imageUrl: '/create_char/subrace/mobile-subrace/Мефистофель_gray.svg' },
    { id: 'mountain-dwarf', name: 'Горный', raceId: 'dwarf', description: 'Дварфы, живущие в горах и славящиеся воинским мастерством.', modifier: { strength: 2 }, imageUrl: '/create_char/subrace/mobile-subrace/Асмодей.svg' },
    { id: 'hill-dwarf', name: 'Холмовый', raceId: 'dwarf', description: 'Дварфы холмов, известные своей выносливостью.', modifier: { wisdom: 1, constitution: 1 }, imageUrl: '/create_char/subrace/mobile-subrace/Асмодей.svg' },
    { id: 'forest-gnome', name: 'Лесной', raceId: 'gnome', description: 'Гномы, живущие в лесах и любящие животных.', modifier: { agility: 1 }, imageUrl: '/create_char/subrace/mobile-subrace/Зариэль.svg' },
    { id: 'rock-gnome', name: 'Скальный', raceId: 'gnome', description: 'Гномы, мастера механизмов и камня.', modifier: { constitution: 1 }, imageUrl: '/create_char/subrace/mobile-subrace/Асмодей.svg' },
    { id: 'deep-gnome', name: 'Глубинный', raceId: 'gnome', description: 'Гномы, живущие глубоко под землёй.', modifier: { agility: 1 }, imageUrl: '/create_char/subrace/mobile-subrace/Мефистофель_gray.svg' },
    { id: 'lightfoot', name: 'Светлые', raceId: 'halfling', description: 'Полурослики, которые умеют ловко скрываться.', modifier: { charisma: 1 }, imageUrl: '/create_char/subrace/mobile-subrace/Мефистофель_gray.svg' },
    { id: 'stout', name: 'Толстопяточные', raceId: 'halfling', description: 'Выносливые полурослики, устойчивые к ядам.', modifier: { constitution: 1 }, imageUrl: '/create_char/subrace/mobile-subrace/Асмодей.svg' },
    { id: 'dragonblood', name: 'Драконокровный', raceId: 'dragonborn', description: 'Драконорожденные с могущественной кровью дракона.', modifier: { charisma: 1 }, imageUrl: '/create_char/subrace/mobile-subrace/Зариэль.svg' },
    { id: 'colored-dragonborn', name: 'Цветные драконорождённые', raceId: 'dragonborn', description: 'Драконорожденные, чья кровь связана с различными цветными драконами.', modifier: {}, imageUrl: '/create_char/subrace/mobile-subrace/Зариэль.svg' },
    { id: 'ravenite', name: 'Равенит', raceId: 'dragonborn', description: 'Драконорожденные с силой и яростью равенайтов.', modifier: { constitution: 1 }, imageUrl: '/create_char/subrace/mobile-subrace/Зариэль.svg' },
    { id: 'zariel', name: 'Зариэль', raceId: 'tiefling', description: 'Тифлинги рода Зариэль, павшего ангела.', modifier: { strength: 1 }, imageUrl: '/create_char/subrace/mobile-subrace/Зариэль.svg' },
    { id: 'asmodeus', name: 'Асмодея', raceId: 'tiefling', description: 'Тифлинги рода Асмодея.', modifier: { intelligence: 1 }, imageUrl: '/create_char/subrace/mobile-subrace/Асмодей.svg' },
    { id: 'mephisto', name: 'Мефистофеля', raceId: 'tiefling', description: 'Тифлинги рода Мефистофель.', modifier: {}, imageUrl: '/create_char/subrace/mobile-subrace/Мефистофель_gray.svg' },
  ],
  classes: [
    { id: 'warrior', name: 'Воин', description: 'Мастер ближнего боя.', recommendedStats: { strength: 14, constitution: 14, agility: 12 } },
    { id: 'sorcerer', name: 'Чародей', description: 'Исполнитель заклинаний.', recommendedStats: { intelligence: 15, wisdom: 12, constitution: 10 }, subclassSelectionLevel: 1 },
    { id: 'warlock', name: 'Колдун', description: 'Обладатель мистической силы.', recommendedStats: { charisma: 15, constitution: 13, wisdom: 10 }, subclassSelectionLevel: 1 },
    { id: 'wizard', name: 'Волшебник', description: 'Мастер магии.', recommendedStats: { intelligence: 15, wisdom: 13, charisma: 10 } },
    { id: 'ranger', name: 'Следопыт', description: 'Воин природы.', recommendedStats: { agility: 14, wisdom: 14, constitution: 12 } },
    { id: 'rogue', name: 'Плут', description: 'Специалист скрытности.', recommendedStats: { agility: 15, charisma: 14, constitution: 10 } },
    { id: 'paladin', name: 'Паладин', description: 'Святой воин.', recommendedStats: { strength: 15, constitution: 12, charisma: 12 } },
    { id: 'monk', name: 'Монах', description: 'Мастер боевых искусств.', recommendedStats: { wisdom: 15, agility: 14, strength: 12 } },
    { id: 'druid', name: 'Друид', description: 'Жрец природы.', recommendedStats: { wisdom: 15, intelligence: 13, charisma: 10 } },
    { id: 'cleric', name: 'Жрец', description: 'Служитель богов.', recommendedStats: { wisdom: 15, charisma: 14, constitution: 12 }, subclassSelectionLevel: 1 },
  ],
  subClasses: [
    { id: 'champion', name: 'Чемпион', classId: 'warrior', description: 'Сильный воин.' },
    { id: 'battle-master', name: 'Мастер боя', classId: 'warrior', description: 'Тактический боец.' },
    { id: 'dragon-bloodline', name: 'Наследие драконьей крови', classId: 'sorcerer', description: 'Ваша магия берёт начало от древних драконов.' },
    { id: 'wild-magic', name: 'Дикая магия', classId: 'sorcerer', description: 'Ваша магия непредсказуема и хаотична.' },
    { id: 'storm-sorcery', name: 'Штормовое колдовство', classId: 'sorcerer', description: 'Ваша магия связана с бурями и стихиями.' },
    { id: 'wild-magic-warlock', name: 'Дикая магия', classId: 'warlock', description: 'Ваша сила исходит из хаоса.' },
    { id: 'dragon-legacy', name: 'Наследие дракона', classId: 'warlock', description: 'Ваш покровитель — древний дракон.' },
    { id: 'storm-warlock', name: 'Штормовое колдовство', classId: 'warlock', description: 'Ваша магия черпает силу из бурь.' },
    { id: 'life-domain', name: 'Домен жизни', classId: 'cleric', description: 'Вы посвятили себя сохранению жизни.' },
    { id: 'light-domain', name: 'Домен света', classId: 'cleric', description: 'Вы несёте свет во тьму.' },
    { id: 'war-domain', name: 'Домен войны', classId: 'cleric', description: 'Вы — оружие вашего божества.' },
    { id: 'necromancy', name: 'Некромантия', classId: 'wizard', description: 'Маг смерти.' },
    { id: 'assassin', name: 'Ассасин', classId: 'rogue', description: 'Убийца.' },
    { id: 'trickster', name: 'Плут', classId: 'rogue', description: 'Обманщик.' },
    { id: 'light-paladin', name: 'Паладин Света', classId: 'paladin', description: 'Паладин света.' },
    { id: 'war-paladin', name: 'Боевой паладин', classId: 'paladin', description: 'Воин веры.' },
    { id: 'beast-master', name: 'Повелитель зверей', classId: 'ranger', description: 'Друг зверей.' },
    { id: 'hunter', name: 'Охотник', classId: 'ranger', description: 'Охотник.' },
  ],
  origins: [
    { id: 'aristocrat', name: 'Аристократ', description: 'Вырос в богатстве и роскоши.', bonus: '+2 Харизма' },
    { id: 'soldier', name: 'Солдат', description: 'Опытный воин, закалённый в битвах.', bonus: '+2 Сила' },
    { id: 'artist', name: 'Артист', description: 'Творческая личность, мастер искусств.', bonus: '+2 к навыку' },
    { id: 'craftsman', name: 'Ремесленник', description: 'Мастер своего дела.', bonus: '+1 к двум навыкам' },
    { id: 'charlatan', name: 'Шарлатан', description: 'Мастер обмана и иллюзий.', bonus: '+2 Ловкость' },
    { id: 'wanderer', name: 'Скиталец', description: 'Путешественник, познавший мир.', bonus: '+2 Мудрость' },
    { id: 'folk-hero', name: 'Народный герой', description: 'Защитник простого народа.', bonus: '+1 ко всем' },
    { id: 'sage', name: 'Мудрец', description: 'Хранитель древних знаний.', bonus: '+2 Интеллект' },
    { id: 'criminal', name: 'Преступник', description: 'Жил вне закона, мастер теней.', bonus: '+2 к атаке' },
    { id: 'novice', name: 'Послушник', description: 'Служитель храма на начальной ступени.', bonus: '+2 Мудрость' },
    { id: 'vagrant', name: 'Бродяга', description: 'Живёт на улицах, полагаясь на себя.', bonus: '+2 Ловкость' },
  ],
  statsInfo: [
    { name: 'Сила', shortName: 'СИЛ', description: 'Физическая мощь.', icon: 'strength' },
    { name: 'Ловкость', shortName: 'ЛОВ', description: 'Скорость.', icon: 'agility' },
    { name: 'Телосложение', shortName: 'ТЕЛ', description: 'Выносливость.', icon: 'constitution' },
    { name: 'Интеллект', shortName: 'ИНТ', description: 'Знания.', icon: 'intelligence' },
    { name: 'Мудрость', shortName: 'МДР', description: 'Интуиция.', icon: 'wisdom' },
    { name: 'Харизма', shortName: 'ХАР', description: 'Общение.', icon: 'charisma' },
  ],
});
