import { CharacterData } from '@/types/character';

export const getCharacterData = (): CharacterData => ({
  steps: [
    { id: 'race', number: 1, title: 'Раса', icon: 'user' },
    { id: 'subrace', number: 2, title: 'Под раса', icon: 'star' },
    { id: 'class', number: 3, title: 'Класс', icon: 'sword' },
    { id: 'origin', number: 4, title: 'Происхождение', icon: 'compass' },
    { id: 'stats', number: 5, title: 'Характеристики', icon: 'chart' },
    { id: 'spells', number: 6, title: 'Заклинания', icon: 'sparkles' },
  ],
  races: [
    { id: 'human', name: 'Человек', description: 'Самые распространённые существа в мире.', modifier: { strength: 1, agility: 1, constitution: 1, intelligence: 1, wisdom: 1, charisma: 1 } },
    { id: 'elf', name: 'Эльф', description: 'Долгоживущие существа с острым чувством магии.', modifier: { agility: 2, wisdom: 1 } },
    { id: 'dwarf', name: 'Дварф', description: 'Мастера кузнечного дела.', modifier: { strength: 2, constitution: 2 } },
    { id: 'halfling', name: 'Халфлинг', description: 'Маленькие, но ловкие существа.', modifier: { agility: 2, charisma: 1 } },
    { id: 'orc', name: 'Орк', description: 'Сильные и выносливые воины.', modifier: { strength: 2, constitution: 1, charisma: -1 } },
  ],
  subRaces: [
    { id: 'human-default', name: 'Обычный человек', raceId: 'human', description: 'Стандартный человек.', modifier: {} },
    { id: 'high-elf', name: 'Высший эльф', raceId: 'elf', description: 'Эльфы магии.', modifier: { intelligence: 1, charisma: 1 } },
    { id: 'wood-elf', name: 'Лесной эльф', raceId: 'elf', description: 'Эльфы природы.', modifier: { agility: 1, wisdom: 1 } },
    { id: 'mountain-dwarf', name: 'Горный дварф', raceId: 'dwarf', description: 'Дварфы гор.', modifier: { strength: 2 } },
    { id: 'hill-dwarf', name: 'Холмовый дварф', raceId: 'dwarf', description: 'Дварфы холмов.', modifier: { wisdom: 1, constitution: 1 } },
  ],
  classes: [
    { id: 'warrior', name: 'Воин', description: 'Мастер ближнего боя.', recommendedStats: { strength: 14, constitution: 14, agility: 12 } },
    { id: 'mage', name: 'Маг', description: 'Исполнитель заклинаний.', recommendedStats: { intelligence: 15, wisdom: 12, constitution: 10 } },
    { id: 'rogue', name: 'Плут', description: 'Специалист скрытности.', recommendedStats: { agility: 15, charisma: 14, constitution: 10 } },
    { id: 'cleric', name: 'Жрец', description: 'Служитель божеств.', recommendedStats: { wisdom: 15, constitution: 12, charisma: 10 } },
    { id: 'ranger', name: 'Следопыт', description: 'Воин природы.', recommendedStats: { agility: 14, wisdom: 14, constitution: 12 } },
  ],
  subClasses: [
    { id: 'champion', name: 'Чемпион', classId: 'warrior', description: 'Сильный воин.' },
    { id: 'battle-master', name: 'Мастер боя', classId: 'warrior', description: 'Тактический боец.' },
    { id: 'evocation', name: 'Эвокация', classId: 'mage', description: 'Маг магии.' },
    { id: 'necromancy', name: 'Некромантия', classId: 'mage', description: 'Маг смерти.' },
    { id: 'assassin', name: 'Ассасин', classId: 'rogue', description: 'Убийца.' },
    { id: 'trickster', name: 'Плут', classId: 'rogue', description: 'Обманщик.' },
    { id: 'light-cleric', name: 'Жрец Света', classId: 'cleric', description: 'Жрец света.' },
    { id: 'war-cleric', name: 'Боевой жрец', classId: 'cleric', description: 'Воин веры.' },
    { id: 'beast-master', name: 'Повелитель зверей', classId: 'ranger', description: 'Друг зверей.' },
    { id: 'hunter', name: 'Охотник', classId: 'ranger', description: 'Охотник.' },
  ],
  origins: [
    { id: 'noble', name: 'Дворянин', description: 'Вырос в богатстве.', bonus: '+1 Харизма' },
    { id: 'soldier', name: 'Солдат', description: 'Опытный воин.', bonus: '+1 Сила' },
    { id: 'scholar', name: 'Учёный', description: 'Образованный.', bonus: '+1 Интеллект' },
    { id: 'peasant', name: 'Крестьянин', description: 'Трудящийся.', bonus: '+1 Телосложение' },
    { id: 'criminal', name: 'Преступник', description: 'Жил вне закона.', bonus: '+1 Ловкость' },
    { id: 'hermit', name: 'Отшельник', description: 'Жил в уединении.', bonus: '+1 Мудрость' },
  ],
  statsInfo: [
    { name: 'Сила', shortName: 'СИЛ', description: 'Физическая мощь.', icon: 'strength' },
    { name: 'Ловкость', shortName: 'ЛОВ', description: 'Скорость.', icon: 'agility' },
    { name: 'Телосложение', shortName: 'ТЕЛ', description: 'Выносливость.', icon: 'constitution' },
    { name: 'Интеллект', shortName: 'ИНТ', description: 'Знания.', icon: 'intelligence' },
    { name: 'Мудрость', shortName: 'МДР', description: 'Интуиция.', icon: 'wisdom' },
    { name: 'Харизма', shortName: 'ХАР', description: 'Общение.', icon: 'charisma' },
  ],
});